USE GD1C2023
GO

SELECT *
FROM sys.objects
WHERE type IN ('FN', 'IF', 'TF') 

SELECT *
FROM sys.procedures

-- LIMPIAR CACHE --
IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'limpiar_cache')
DROP PROCEDURE limpiar_cache
GO
CREATE PROCEDURE limpiar_cache
AS
BEGIN
DBCC FREEPROCCACHE WITH NO_INFOMSGS
DBCC DROPCLEANBUFFERS WITH NO_INFOMSGS
END
GO
-- PROCEDURE DROPEAR TABLAS
IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'dropear_tablas')
DROP PROCEDURE dropear_tablas
GO
CREATE PROCEDURE dropear_tablas
AS
BEGIN
BEGIN TRANSACTION
BEGIN TRY
IF OBJECT_ID('NEW_MODEL.PAGO', 'U') IS NOT NULL DROP TABLE NEW_MODEL.PAGO
IF OBJECT_ID('NEW_MODEL.MENSAJERIA', 'U') IS NOT NULL DROP TABLE NEW_MODEL.MENSAJERIA
IF OBJECT_ID('NEW_MODEL.ENVIO_MENSAJERIA', 'U') IS NOT NULL DROP TABLE NEW_MODEL.ENVIO_MENSAJERIA
IF OBJECT_ID('NEW_MODEL.MENSAJERIA_ESTADO', 'U') IS NOT NULL DROP TABLE NEW_MODEL.MENSAJERIA_ESTADO
IF OBJECT_ID('NEW_MODEL.PAQUETE', 'U') IS NOT NULL DROP TABLE NEW_MODEL.PAQUETE
IF OBJECT_ID('NEW_MODEL.TIPO_PAQUETE', 'U') IS NOT NULL DROP TABLE NEW_MODEL.TIPO_PAQUETE
IF OBJECT_ID('NEW_MODEL.RECLAMO', 'U') IS NOT NULL DROP TABLE NEW_MODEL.RECLAMO
IF OBJECT_ID('NEW_MODEL.CUPON', 'U') IS NOT NULL DROP TABLE NEW_MODEL.CUPON
IF OBJECT_ID('NEW_MODEL.CUPON_TIPO', 'U') IS NOT NULL DROP TABLE NEW_MODEL.CUPON_TIPO
IF OBJECT_ID('NEW_MODEL.OPERADOR', 'U') IS NOT NULL DROP TABLE NEW_MODEL.OPERADOR
IF OBJECT_ID('NEW_MODEL.ESTADO_RECLAMO', 'U') IS NOT NULL DROP TABLE NEW_MODEL.ESTADO_RECLAMO
IF OBJECT_ID('NEW_MODEL.TIPO_RECLAMO', 'U') IS NOT NULL DROP TABLE NEW_MODEL.TIPO_RECLAMO
IF OBJECT_ID('NEW_MODEL.ITEM', 'U') IS NOT NULL DROP TABLE NEW_MODEL.ITEM
IF OBJECT_ID('NEW_MODEL.LOCAL_PRODUCTO', 'U') IS NOT NULL DROP TABLE NEW_MODEL.LOCAL_PRODUCTO
IF OBJECT_ID('NEW_MODEL.PRODUCTO', 'U') IS NOT NULL DROP TABLE NEW_MODEL.PRODUCTO
IF OBJECT_ID('NEW_MODEL.HORARIO', 'U') IS NOT NULL DROP TABLE NEW_MODEL.HORARIO
IF OBJECT_ID('NEW_MODEL.DIA', 'U') IS NOT NULL DROP TABLE NEW_MODEL.DIA
IF OBJECT_ID('NEW_MODEL.LOCAL', 'U') IS NOT NULL DROP TABLE NEW_MODEL.LOCAL
IF OBJECT_ID('NEW_MODEL.TIPO_LOCAL', 'U') IS NOT NULL DROP TABLE NEW_MODEL.TIPO_LOCAL
IF OBJECT_ID('NEW_MODEL.CATEGORIA', 'U') IS NOT NULL DROP TABLE NEW_MODEL.CATEGORIA
IF OBJECT_ID('NEW_MODEL.PEDIDO', 'U') IS NOT NULL DROP TABLE NEW_MODEL.PEDIDO
IF OBJECT_ID('NEW_MODEL.MEDIO_PAGO', 'U') IS NOT NULL DROP TABLE NEW_MODEL.MEDIO_PAGO
IF OBJECT_ID('NEW_MODEL.TARJETA', 'U') IS NOT NULL DROP TABLE NEW_MODEL.TARJETA
IF OBJECT_ID('NEW_MODEL.MARCA_TARJETA', 'U') IS NOT NULL DROP TABLE NEW_MODEL.MARCA_TARJETA
IF OBJECT_ID('NEW_MODEL.PEDIDO_ESTADO', 'U') IS NOT NULL DROP TABLE NEW_MODEL.PEDIDO_ESTADO
IF OBJECT_ID('NEW_MODEL.PEDIDO_ENVIO', 'U') IS NOT NULL DROP TABLE NEW_MODEL.PEDIDO_ENVIO
IF OBJECT_ID('NEW_MODEL.DIRECCION_USUARIO', 'U') IS NOT NULL DROP TABLE NEW_MODEL.DIRECCION_USUARIO
IF OBJECT_ID('NEW_MODEL.ALTA', 'U') IS NOT NULL DROP TABLE NEW_MODEL.ALTA
IF OBJECT_ID('NEW_MODEL.REPARTIDOR', 'U') IS NOT NULL DROP TABLE NEW_MODEL.REPARTIDOR
IF OBJECT_ID('NEW_MODEL.TIPO_MOVILIDAD', 'U') IS NOT NULL DROP TABLE NEW_MODEL.TIPO_MOVILIDAD
IF OBJECT_ID('NEW_MODEL.USUARIO', 'U') IS NOT NULL DROP TABLE NEW_MODEL.USUARIO
IF OBJECT_ID('NEW_MODEL.LOCALIDAD', 'U') IS NOT NULL DROP TABLE NEW_MODEL.LOCALIDAD
IF OBJECT_ID('NEW_MODEL.PROVINCIA', 'U') IS NOT NULL DROP TABLE NEW_MODEL.PROVINCIA

PRINT('Tablas dropeadas')
COMMIT TRANSACTION;
END TRY
BEGIN CATCH
ROLLBACK TRANSACTION;
THROW 50001, 'Error al hacer DROP TABLAS',1;
END CATCH
END
GO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'borrar_todo')
DROP PROCEDURE borrar_todo
GO
CREATE PROCEDURE borrar_todo
AS BEGIN

exec dropear_tablas
-- ELIMINACION PREVENTIVA DE INDICES --
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UNIQUE_NULL_PEDIDO_NRO')
DROP INDEX UNIQUE_NULL_PEDIDO_NRO ON NEW_MODEL.PAGO;

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'UNIQUE_NULL_MENSAJERIA_NRO')
DROP INDEX UNIQUE_NULL_MENSAJERIA_NRO ON NEW_MODEL.PAGO;

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_PEDIDO_ENVIO_REPARTIDOR_FECHA_DIRECCION')
DROP INDEX IX_PEDIDO_ENVIO_REPARTIDOR_FECHA_DIRECCION ON NEW_MODEL.PEDIDO_ENVIO;

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_ENVIO_MENSAJERIA_REPARTIDOR_FECHA_DIRECCION')
DROP INDEX IX_ENVIO_MENSAJERIA_REPARTIDOR_FECHA_DIRECCION ON NEW_MODEL.ENVIO_MENSAJERIA;

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_LOCALIDAD')
DROP INDEX IX_LOCALIDAD ON NEW_MODEL.LOCALIDAD;

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_REPARTIDOR')
DROP INDEX IX_REPARTIDOR ON NEW_MODEL.REPARTIDOR;

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_USUARIO')
DROP INDEX IX_USUARIO ON NEW_MODEL.USUARIO;

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_DIRECCION_USUARIO')
DROP INDEX IX_DIRECCION_USUARIO ON NEW_MODEL.DIRECCION_USUARIO;

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_LOCAL')
DROP INDEX IX_LOCAL ON NEW_MODEL.LOCAL;

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_TARJETA')
DROP INDEX IX_TARJETA ON NEW_MODEL.TARJETA;

IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_OPERADOR')
DROP INDEX IX_OPERADOR ON NEW_MODEL.OPERADOR;


IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_PROVINCIAS')
DROP PROCEDURE MIGRAR_PROVINCIAS

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_LOCALIDADES')
DROP PROCEDURE MIGRAR_LOCALIDADES

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_TIPO_MOVILIDAD')
DROP PROCEDURE MIGRAR_TIPO_MOVILIDAD

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_REPARTIDOR')
DROP PROCEDURE MIGRAR_REPARTIDOR

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_DIRECCION_USUARIO')
DROP PROCEDURE MIGRAR_DIRECCION_USUARIO
    
IF EXISTS(SELECT [name] FROM sys.all_objects WHERE [name] = 'MIGRAR_LOCALIDADES')
DROP PROCEDURE MIGRAR_LOCALIDADES

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_USUARIOS')
DROP PROCEDURE MIGRAR_USUARIOS

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_TIPO_MOVILIDAD')
DROP PROCEDURE MIGRAR_TIPO_MOVILIDAD

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_REPARTIDOR')
DROP PROCEDURE MIGRAR_REPARTIDOR

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_TIPO_LOCAL')
DROP PROCEDURE MIGRAR_TIPO_LOCAL

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_LOCAL')
DROP PROCEDURE MIGRAR_LOCAL

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_DIA')
DROP PROCEDURE MIGRAR_DIA

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_HORARIO')
DROP PROCEDURE MIGRAR_HORARIO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_PRODUCTO')
DROP PROCEDURE MIGRAR_PRODUCTO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_PEDIDO_ENVIO')
DROP PROCEDURE MIGRAR_PEDIDO_ENVIO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_PEDIDO_ESTADO')
DROP PROCEDURE MIGRAR_PEDIDO_ESTADO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_PEDIDO')
DROP PROCEDURE MIGRAR_PEDIDO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_LOCAL_PRODUCTO')
DROP PROCEDURE MIGRAR_LOCAL_PRODUCTO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_MENSAJERIA_ESTADO')
DROP PROCEDURE MIGRAR_MENSAJERIA_ESTADO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_TIPO_PAQUETE')
DROP PROCEDURE MIGRAR_TIPO_PAQUETE

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_PAQUETE')
DROP PROCEDURE MIGRAR_PAQUETE

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_ALTA')
DROP PROCEDURE MIGRAR_ALTA

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_MEDIO_PAGO')
DROP PROCEDURE MIGRAR_MEDIO_PAGO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_MARCA_TARJETA')
DROP PROCEDURE MIGRAR_MARCA_TARJETA

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_TARJETA')
DROP PROCEDURE MIGRAR_TARJETA

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_PAGO')
DROP PROCEDURE MIGRAR_PAGO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_MENSAJERIA')
DROP PROCEDURE MIGRAR_MENSAJERIA;

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_ENVIO_MENSAJERIA')
DROP PROCEDURE MIGRAR_ENVIO_MENSAJERIA

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_TIPO_RECLAMO')
DROP PROCEDURE MIGRAR_TIPO_RECLAMO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_ESTADO_RECLAMO')
DROP PROCEDURE MIGRAR_ESTADO_RECLAMO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_OPERADOR')
DROP PROCEDURE MIGRAR_OPERADOR

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_CUPON_TIPO')
DROP PROCEDURE MIGRAR_CUPON_TIPO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_CUPON')
DROP PROCEDURE MIGRAR_CUPON

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_RECLAMO')
DROP PROCEDURE MIGRAR_RECLAMO

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'MIGRAR_ITEM')
DROP PROCEDURE MIGRAR_ITEM

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'crear_tablas')
DROP PROCEDURE crear_tablas

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'migrar_tablas')
DROP PROCEDURE migrar_tablas

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'dropear_tablas')
DROP PROCEDURE dropear_tablas

IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'borrar_todo')
DROP PROCEDURE borrar_todo

IF EXISTS(SELECT [name] FROM sys.all_objects WHERE [name] = 'obtenerProvinciaNro')
DROP FUNCTION obtenerProvinciaNro

IF EXISTS(SELECT [name] FROM sys.all_objects WHERE [name] = 'obtenerLocalidadNro')
DROP FUNCTION obtenerLocalidadNro

IF EXISTS(SELECT [name] FROM sys.all_objects WHERE [name] = 'obtenerTipoMovilidadNro')
DROP FUNCTION obtenerTipoMovilidadNro
    
IF EXISTS(SELECT [name] FROM sys.all_objects WHERE [name] = 'obtenerUsuarioNro')
DROP FUNCTION obtenerUsuarioNro

IF EXISTS(SELECT [name] FROM sys.all_objects WHERE [name] = 'obtenerCategoriaNro')
DROP FUNCTION obtenerCategoriaNro

IF EXISTS(SELECT [name] FROM sys.all_objects WHERE [name] = 'obtenerTipoLocalNro')
DROP FUNCTION obtenerTipoLocalNro

IF EXISTS(SELECT [name] FROM sys.all_objects WHERE [name] = 'obtenerLocalNro')
DROP FUNCTION obtenerLocalNro

IF EXISTS(SELECT [name] FROM sys.all_objects WHERE [name] = 'obtenerDiaNro')
DROP FUNCTION obtenerDiaNro

IF EXISTS(SELECT [name] FROM sys.all_objects WHERE [name] = 'obtenerRepartidorNro')
DROP FUNCTION obtenerRepartidorNro

IF EXISTS(SELECT [name] FROM sys.all_objects WHERE [name] = 'obtenerDireccionUsuarioNro')
DROP FUNCTION obtenerDireccionUsuarioNro

IF EXISTS(SELECT [name] FROM sys.all_objects WHERE [name] = 'obtenerProductoNro')
DROP FUNCTION obtenerProductoNro

IF EXISTS(SELECT [name] FROM sys.all_objects WHERE [name] = 'obtenerPedidoEstadoNro')
DROP FUNCTION obtenerPedidoEstadoNro

IF EXISTS(SELECT [name] FROM sys.all_objects WHERE [name] = 'obtenerMedioPagoNro')
DROP FUNCTION obtenerMedioPagoNro

IF EXISTS(SELECT [name] FROM sys.all_objects WHERE [name] = 'obtenerPedidoEnvioNro')
DROP FUNCTION obtenerPedidoEnvioNro

IF EXISTS(SELECT [name] FROM sys.all_objects WHERE [name] = 'obtenerMarcaTarjetaNro')
DROP FUNCTION obtenerMarcaTarjetaNro

IF EXISTS(SELECT [name] FROM sys.all_objects WHERE [name] = 'obtenerTarjetaNro')
DROP FUNCTION obtenerTarjetaNro

IF EXISTS(SELECT [name] FROM sys.all_objects WHERE [name] = 'obtenertipoPaqueteNro')
DROP FUNCTION obtenertipoPaqueteNro

IF EXISTS(SELECT [name] FROM sys.all_objects WHERE [name] = 'obtenerEstadoNro')
DROP FUNCTION obtenerEstadoNro

IF EXISTS(SELECT [name] FROM sys.all_objects WHERE [name] = 'obtenerReclamoNro')
DROP FUNCTION obtenerReclamoNro

IF EXISTS(SELECT [name] FROM sys.all_objects WHERE [name] = 'obtenerCuponNro')
DROP FUNCTION obtenerCuponNro

IF EXISTS(SELECT [name] FROM sys.all_objects WHERE [name] = 'obtenerTipoReclamo')
DROP FUNCTION obtenerTipoReclamo

IF EXISTS(SELECT [name] FROM sys.all_objects WHERE [name] = 'obtenerEstadoReclamoNro')
DROP FUNCTION obtenerEstadoReclamoNro

IF EXISTS(SELECT [name] FROM sys.all_objects WHERE [name] = 'obtenerOperadorNro')
DROP FUNCTION obtenerOperadorNro

IF EXISTS(SELECT [name] FROM sys.all_objects WHERE [name] = 'obtenerCuponTipoNro')
DROP FUNCTION obtenerCuponTipoNro

IF EXISTS(SELECT [name] FROM sys.all_objects WHERE [name] = 'obtenerEnvioMensajeriaNro')
DROP FUNCTION obtenerEnvioMensajeriaNro

PRINT ('TABLAS FUNCIONES Y PROCEDURES ELIMINADOS')
END
GO



-----------------------------------------------------------------------ZONA DE TESTEO DE SANTI, NO ME BORRES PLS----------------------------------------------------------------------------------------------
--select * from NEW_MODEL.MENSAJERIA;
--exec borrar_todo;
--exec crear_tablas;
--exec migrar_tablas;
--select * from new_model.ENVIO_MENSAJERIA ;

--select REPARTIDOR_NRO, REPARTIDOR_DNI from NEW_MODEL.REPARTIDOR order by REPARTIDOR_NRO;
--select PEDIDO_NRO from NEW_MODEL.PEDIDO;
--SELECT * FROM NEW_MODEL.MEDIO_PAGO_TIPO
--exec MIGRAR_OPERADOR;
--EXEC MIGRAR_CUPON_RECLAMO;
--DROP FUNCTION obtenerCuponNro
--DROP FUNCTION obtenerReclamoNro

-- create index REPNRO_FECHA
-- on NEW_MODEL.PEDIDO_ENVIO (PEDIDO_ENVIO_REPARTIDOR_NRO, PEDIDO_ENVIO_FECHA);

-- DROP INDEX DEST_FECHA_KM
-- --(ENVIO_MENSAJERIA_DIR_DEST,ENVIO_MENSAJERIA_FECHA,ENVIO_MENSAJERIA_KM)
-- create index DEST_FECHA_KM
-- on NEW_MODEL.ENVIO_MENSAJERIA (ENVIO_MENSAJERIA_DIR_DEST,ENVIO_MENSAJERIA_FECHA,ENVIO_MENSAJERIA_KM);
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

