USE GD1C2023
GO

SELECT *
FROM sys.objects
WHERE type IN ('FN', 'IF', 'TF') 

SELECT *
FROM sys.procedures

EXEC borrar_todo

exec crear_tablas
exec migrar_tablas

EXEC crear_tablas
exec migrar_tablas


SELECT DISTINCT LOCAL_NOMBRE, LOCAL_DIRECCION PRODUCTO_LOCAL_CODIGO FROM gd_esquema.Maestra where PRODUCTO_LOCAL_CODIGO IS NOT NULL 
ORDER BY LOCAL_NOMBRE

SELECT DISTINCT REPARTIDOR_DNI, LOCAL_NOMBRE, LOCAL_LOCALIDAD, PEDIDO_NRO FROM gd_esquema.Maestra WHERE REPARTIDOR_DNI IS NOT NULL ORDER BY  REPARTIDOR_DNI, LOCAL_NOMBRE
SELECT DISTINCT REPARTIDOR_DNI, LOCAL_NOMBRE, ENVIO_MENSAJERIA_LOCALIDAD, ENVIO_MENSAJERIA_NRO FROM gd_esquema.Maestra WHERE REPARTIDOR_DNI IS NOT NULL ORDER BY  REPARTIDOR_DNI, LOCAL_NOMBRE

SELECT DISTINCT REPARTIDOR_DNI, LOCAL_NOMBRE, LOCAL_LOCALIDAD, ENVIO_MENSAJERIA_LOCALIDAD FROM gd_esquema.Maestra WHERE REPARTIDOR_DNI IS NOT NULL ORDER BY  REPARTIDOR_DNI, LOCAL_NOMBRE

-- ESTA CONSULTA NOS DEVUELVE UNA ESPECIE "HISTORIAL", DE LAS LOCALIDADES DONDE ESTUVO TRABAJANDO EL REPARTIDOR, YA SEA POR PEDIDO O POR ENVIO, "LA MAS ACTUAL" ACTUAL DEBERIA SER LA LOCALIDAD ACTIVA, EL RESTO NO
-- PODEMOS USAR LA FECHA O FECHA DE ENTREGA COMO ULTIMO LUGAR DONDE ESTUVO EL REPARTIDOR

SELECT DISTINCT PEDIDO_NRO, REPARTIDOR_DNI, LOCAL_NOMBRE, LOCAL_LOCALIDAD, PEDIDO_FECHA ,PEDIDO_FECHA_ENTREGA FROM gd_esquema.Maestra WHERE REPARTIDOR_DNI IS NOT NULL ORDER BY  REPARTIDOR_DNI, LOCAL_NOMBRE

SELECT DISTINCT PEDIDO_NRO, REPARTIDOR_DNI, PEDIDO_FECHA, PEDIDO_FECHA_ENTREGA FROM gd_esquema.Maestra WHERE PEDIDO_NRO IS NOT NULL ORDER BY  PEDIDO_FECHA DESC
-- ESTA FUNCION NOS  ORDENA LOS PEDIDOS POR FECHA EN ORDEN DESCENDENTE Y SELECCIONANDO EL PRIMERO OBTENEMOS EL MAS ACTUAL 

SELECT * FROM(
SELECT DISTINCT PEDIDO_NRO AS NRO_OP,LOCAL_PROVINCIA AS PROVINCIA, LOCAL_LOCALIDAD AS LOCALIDAD, REPARTIDOR_DNI, PEDIDO_FECHA AS FECHA FROM gd_esquema.Maestra WHERE PEDIDO_NRO IS NOT NULL
UNION 
SELECT DISTINCT ENVIO_MENSAJERIA_NRO AS NRO_OP, ENVIO_MENSAJERIA_PROVINCIA AS PROVINCIA, ENVIO_MENSAJERIA_LOCALIDAD AS LOCALIDAD, REPARTIDOR_DNI, ENVIO_MENSAJERIA_FECHA AS FECHA FROM gd_esquema.Maestra WHERE ENVIO_MENSAJERIA_NRO IS NOT NULL
) T WHERE T.REPARTIDOR_DNI = 1295290
ORDER BY FECHA DESC 

SELECT * FROM NEW_MODEL.ALTA

-- ESTE UNION NOS DA LOS ENVIOS + LOS PEDIDOS CON SUS FECHAS, TODOS EN UNA SOLA TABLA, SI ORDENAMOS POR DESC OBTENDREMOS LA MAS ACTUAL


                    borrar_todo
                    crear_tablas
                    migrar_tablas

                    mostrar_funciones
                    mostrar_procedures


select * from new_model.PEDIDO

SELECT * FROM NEW_MODEL.LOCAL_PRODUCTO
select * from gd_esquema.Maestra WHERE pedido_nro = 61254


		SELECT DISTINCT 
        LOCAL_NOMBRE,
        LOCAL_DIRECCION, 
        PRODUCTO_LOCAL_CODIGO,
        PEDIDO_NRO,
        SUM(PRODUCTO_CANTIDAD) as PRODUCTO_CANTIDAD,
        PRODUCTO_LOCAL_PRECIO
        FROM gd_esquema.Maestra where PEDIDO_NRO IS NOT NULL AND PRODUCTO_LOCAL_CODIGO IS NOT NULL
        GROUP BY 
        LOCAL_NOMBRE,
        LOCAL_DIRECCION,
        PRODUCTO_LOCAL_CODIGO,
        PRODUCTO_LOCAL_PRECIO,
        PEDIDO_NRO
        ORDER BY PEDIDO_NRO

        SELECT DISTINCT 
        LOCAL_NOMBRE,
        LOCAL_DIRECCION, 
        PRODUCTO_LOCAL_CODIGO, 
        PEDIDO_NRO,
        PRODUCTO_LOCAL_PRECIO,
        PRODUCTO_CANTIDAD
        FROM gd_esquema.Maestra where PEDIDO_NRO IS NOT NULL AND PRODUCTO_LOCAL_CODIGO IS NOT NULL 
        ORDER BY PEDIDO_NRO

        SELECT * FROM gd_esquema.Maestra WHERE PEDIDO_NRO IS NOT NULL ORDER BY PEDIDO_NRO
        print(NULL +4+1)

