USE GD1C2023
GO

-- CREACION DEL SCHEMA --

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'BI_MODEL')
BEGIN
    EXEC('CREATE SCHEMA BI_MODEL');
END

-- LIMPIAR CACHE --
IF EXISTS(SELECT [name] FROM sys.procedures WHERE [name] = 'limpiar_cache')
DROP PROCEDURE limpiar_cache
GO
CREATE PROCEDURE limpiar_cache
AS
BEGIN
DBCC FREEPROCCACHE WITH NO_INFOMSGS
DBCC DROPCLEANBUFFERS WITH NO_INFOMSGS
END
GO


IF OBJECT_ID('BI_MODEL.PROVINCIA', 'U') IS NULL
    CREATE TABLE BI_MODEL.PROVINCIA(
	PROVINCIA_NRO int IDENTITY PRIMARY KEY,
	PROVINCIA_NOMBRE nvarchar(255) NOT NULL UNIQUE
	);


IF OBJECT_ID('BI_MODEL.LOCALIDAD', 'U') IS NULL
    CREATE TABLE NEW_MODEL.LOCALIDAD(
        LOCALIDAD_NRO int IDENTITY PRIMARY KEY,
        LOCALIDAD_PRIVINCIA_NRO int REFERENCES NEW_MODEL.PROVINCIA,
        LOCALIDAD_NOMBRE nvarchar(255) NOT NULL,
    );


  IF OBJECT_ID('BI_MODEL.TIPO_MOVILIDAD', 'U') IS NULL
    CREATE TABLE BI_MODEL.TIPO_MOVILIDAD(
    TIPO_MOVILIDAD_NRO int IDENTITY PRIMARY KEY,
    TIPO_MOVILIDAD_NOMBRE nvarchar(50) NOT NULL UNIQUE
    );


	 IF OBJECT_ID('BI_MODEL.REPARTIDOR', 'U') IS NULL
    CREATE TABLE NEW_MODEL.REPARTIDOR(
        REPARTIDOR_NRO int IDENTITY PRIMARY KEY,
        REPARTIDOR_TIPO_MOVILIDAD_NRO int REFERENCES BI_MODEL.TIPO_MOVILIDAD,
        REPARTIDOR_EDAD int NOT NULL,
    );  




	 IF OBJECT_ID('NEW_MODEL.USUARIO', 'U') IS NULL
    CREATE TABLE NEW_MODEL.USUARIO(
        USUARIO_NRO int IDENTITY PRIMARY KEY, 
		MEDIOS_DE_PAGO int REFERENCES BI_MODEL.MEDIO_PAGO    
        EDAD int NOT NULL,

    );

	IF OBJECT_ID('BI_MODEL.CATEGORIA', 'U') IS NULL
    CREATE TABLE BI_MODEL.CATEGORIA(
        CATEGORIA_NRO int IDENTITY PRIMARY KEY,
        CATEGORIA_NOMBRE nvarchar(50) NOT NULL UNIQUE,
    );

    IF OBJECT_ID('BI_MODEL.TIPO_LOCAL', 'U') IS NULL
    CREATE TABLE BI_MODEL.TIPO_LOCAL(
        TIPO_LOCAL_NRO int IDENTITY PRIMARY KEY,
        TIPO_LOCAL_CATEGORIA_NRO int REFERENCES BI_MODEL.CATEGORIA NULL,
        TIPO_LOCAL_NOMBRE nvarchar(50) NOT NULL UNIQUE
    );


    IF OBJECT_ID('BI_MODEL.LOCAL', 'U') IS NULL
    CREATE TABLE BI_MODEL.LOCAL(
        LOCAL_NRO int IDENTITY PRIMARY KEY,
        LOCAL_TIPO_LOCAL_NRO int REFERENCES BI_MODEL.TIPO_LOCAL,
    );


	 IF OBJECT_ID('BI_MODEL.ESTADO_RECLAMO', 'U') IS NULL
    CREATE TABLE BI_MODEL.ESTADO_RECLAMO(
        ESTADO_RECLAMO_NRO int IDENTITY PRIMARY KEY,
        ESTADO_RECLAMO_NOMBRE NVARCHAR(50) NOT NULL UNIQUE,
    );


	IF OBJECT_ID('BI_MODEL.PEDIDO_ESTADO', 'U') IS NULL
    CREATE TABLE BI_MODEL.PEDIDO_ESTADO(
        PEDIDO_ESTADO_NRO int IDENTITY PRIMARY KEY,
        PEDIDO_ESTADO nvarchar(50) NOT NULL UNIQUE
    );

	IF OBJECT_ID('BI_MODEL.MENSAJERIA_ESTADO', 'U') IS NULL
    CREATE TABLE BI_MODEL.MENSAJERIA_ESTADO(
        MENSAJERIA_ESTADO_NRO int IDENTITY PRIMARY KEY,
        ENVIO_MENSAJERIA_ESTADO nvarchar(50) NOT NULL UNIQUE,
    );

	 IF OBJECT_ID('BI_MODEL.CUPON', 'U') IS NULL
    CREATE TABLE BI_MODEL.CUPON(
        CUPONES_NRO int IDENTITY PRIMARY KEY,
        CANTIDAD_CUPONES_USADOS int,
		MONTO_TOTAL_CUPONES decimal(18,2)
    );


			IF OBJECT_ID('BI_MODEL.HORARIO', 'U') IS NULL
    CREATE TABLE BI_MODEL.HORARIO(
		HORARIO_NRO int IDENTITY PRIMARY KEY,
		HORARIO_FRANJA NVARCHAR(50)
		);


	IF OBJECT_ID('BI_MODEL.FECHA_INICIAL', 'U') IS NULL
    CREATE TABLE BI_MODEL.FECHA_INICIAL(
		FECHA_NRO int IDENTITY PRIMARY KEY,
		ANIO int,
		MES int,
		DIA nvarchar(50),
		HORARIO int references BI_MODEL.HORARIO,
		HORARIO_EXACTO decimal(18,2)
		);

		
			IF OBJECT_ID('BI_MODEL.OPERADOR', 'U') IS NULL
    CREATE TABLE BI_MODEL.OPERADOR(
		OPERADOR_NRO int IDENTITY PRIMARY KEY,
		OPERADOR_EDAD int not null
		);	
	



    IF OBJECT_ID('BI_MODEL.PEDIDO', 'U') IS NULL
    CREATE TABLE BI_MODEL.PEDIDO(
		PEDIDO_NRO int IDENTITY PRIMARY KEY,
		FECHA_INICIAL_NRO int REFERENCES BI_MODEL.FECHA_INICIAL,
		FECHA_FINAL_NRO int REFERENCES BI_MODEL.FECHA_FINAL,
		LOCALIDAD_NRO int REFERENCES BI_MODEL.LOCALIDAD,
		TIPO_LOCAL int REFERENCES BI_MODEL.LOCAL,
		REPARTIDOR_NRO int REFERENCES BI_MODEL.REPARTIDOR,
		RECLAMO_NRO int REFERENCES BI_MODEL.RECLAMO,
		CUPON_NRO int REFERENCES BI_MODEL.CUPON,
		ESTADO_NRO int REFERENCES BI_MODEL.PEDIDO_ESTADO,
		PRECIO decimal(18,2) not null,
		CALIFICACION int
		);


    IF OBJECT_ID('BI_MODEL.MENSAJERIA', 'U') IS NULL
    CREATE TABLE BI_MODEL.MENSAJERIA(
		RECLAMO_NRO int IDENTITY PRIMARY KEY,
		FECHA_INICIAL_NRO int REFERENCES BI_MODEL.FECHA_INICIAL,
		FECHA_FINAL_NRO int REFERENCES BI_MODEL.FECHA_FINAL,
		LOCALIDAD_NRO int REFERENCES BI_MODEL.LOCALIDAD,
		REPARTIDOR_NRO int REFERENCES BI_MODEL.REPARTIDOR,
		TIPO_PAQUETE int REFERENCES BI_MODEL.TIPO_PAQUETE,
		USUARIO_NRO int REFERENCES BI_MODEL.USUARIO,
		ESTADO_NRO int REFERENCES BI_MODEL.MENSAJERIA_ESTADO,
		VALOR_ASEGURADO decimal(18,2) not null,
		);